export const COUNTRIES = [
  { value: 'AF', label: 'Afeganistão (AF)' },
  { value: 'AL', label: 'Albânia (AL)' },
  { value: 'DZ', label: 'Argélia (DZ)' },
  { value: 'AR', label: 'Argentina (AR)' },
  { value: 'AU', label: 'Austrália (AU)' },
  { value: 'AT', label: 'Áustria (AT)' },
  { value: 'BD', label: 'Bangladesh (BD)' },
  { value: 'BE', label: 'Bélgica (BE)' },
  { value: 'BR', label: 'Brasil (BR)' },
  { value: 'BG', label: 'Bulgária (BG)' },
  { value: 'CA', label: 'Canadá (CA)' },
  { value: 'CL', label: 'Chile (CL)' },
  { value: 'CN', label: 'China (CN)' },
  { value: 'CO', label: 'Colômbia (CO)' },
  { value: 'CR', label: 'Costa Rica (CR)' },
  { value: 'HR', label: 'Croácia (HR)' },
  { value: 'CU', label: 'Cuba (CU)' },
  { value: 'CZ', label: 'República Tcheca (CZ)' },
  { value: 'DK', label: 'Dinamarca (DK)' },
  { value: 'DO', label: 'República Dominicana (DO)' },
  { value: 'EC', label: 'Equador (EC)' },
  { value: 'EG', label: 'Egito (EG)' },
  { value: 'SV', label: 'El Salvador (SV)' },
  { value: 'EE', label: 'Estônia (EE)' },
  { value: 'FI', label: 'Finlândia (FI)' },
  { value: 'FR', label: 'França (FR)' },
  { value: 'DE', label: 'Alemanha (DE)' },
  { value: 'GR', label: 'Grécia (GR)' },
  { value: 'GT', label: 'Guatemala (GT)' },
  { value: 'HN', label: 'Honduras (HN)' },
  { value: 'HK', label: 'Hong Kong (HK)' },
  { value: 'HU', label: 'Hungria (HU)' },
  { value: 'IS', label: 'Islândia (IS)' },
  { value: 'IN', label: 'Índia (IN)' },
  { value: 'ID', label: 'Indonésia (ID)' },
  { value: 'IR', label: 'Irã (IR)' },
  { value: 'IQ', label: 'Iraque (IQ)' },
  { value: 'IE', label: 'Irlanda (IE)' },
  { value: 'IL', label: 'Israel (IL)' },
  { value: 'IT', label: 'Itália (IT)' },
  { value: 'JM', label: 'Jamaica (JM)' },
  { value: 'JP', label: 'Japão (JP)' },
  { value: 'JO', label: 'Jordânia (JO)' },
  { value: 'KZ', label: 'Cazaquistão (KZ)' },
  { value: 'KE', label: 'Quênia (KE)' },
  { value: 'KR', label: 'Coreia do Sul (KR)' },
  { value: 'KW', label: 'Kuwait (KW)' },
  { value: 'LV', label: 'Letônia (LV)' },
  { value: 'LB', label: 'Líbano (LB)' },
  { value: 'LT', label: 'Lituânia (LT)' },
  { value: 'LU', label: 'Luxemburgo (LU)' },
  { value: 'MY', label: 'Malásia (MY)' },
  { value: 'MX', label: 'México (MX)' },
  { value: 'MA', label: 'Marrocos (MA)' },
  { value: 'NL', label: 'Holanda (NL)' },
  { value: 'NZ', label: 'Nova Zelândia (NZ)' },
  { value: 'NI', label: 'Nicarágua (NI)' },
  { value: 'NG', label: 'Nigéria (NG)' },
  { value: 'NO', label: 'Noruega (NO)' },
  { value: 'PK', label: 'Paquistão (PK)' },
  { value: 'PA', label: 'Panamá (PA)' },
  { value: 'PY', label: 'Paraguai (PY)' },
  { value: 'PE', label: 'Peru (PE)' },
  { value: 'PH', label: 'Filipinas (PH)' },
  { value: 'PL', label: 'Polônia (PL)' },
  { value: 'PT', label: 'Portugal (PT)' },
  { value: 'PR', label: 'Porto Rico (PR)' },
  { value: 'QA', label: 'Catar (QA)' },
  { value: 'RO', label: 'Romênia (RO)' },
  { value: 'RU', label: 'Rússia (RU)' },
  { value: 'SA', label: 'Arábia Saudita (SA)' },
  { value: 'RS', label: 'Sérvia (RS)' },
  { value: 'SG', label: 'Singapura (SG)' },
  { value: 'SK', label: 'Eslováquia (SK)' },
  { value: 'SI', label: 'Eslovênia (SI)' },
  { value: 'ZA', label: 'África do Sul (ZA)' },
  { value: 'ES', label: 'Espanha (ES)' },
  { value: 'LK', label: 'Sri Lanka (LK)' },
  { value: 'SE', label: 'Suécia (SE)' },
  { value: 'CH', label: 'Suíça (CH)' },
  { value: 'SY', label: 'Síria (SY)' },
  { value: 'TW', label: 'Taiwan (TW)' },
  { value: 'TH', label: 'Tailândia (TH)' },
  { value: 'TR', label: 'Turquia (TR)' },
  { value: 'UA', label: 'Ucrânia (UA)' },
  { value: 'AE', label: 'Emirados Árabes (AE)' },
  { value: 'GB', label: 'Reino Unido (GB)' },
  { value: 'US', label: 'Estados Unidos (US)' },
  { value: 'UY', label: 'Uruguai (UY)' },
  { value: 'VE', label: 'Venezuela (VE)' },
  { value: 'VN', label: 'Vietnã (VN)' },
  { value: 'YE', label: 'Iêmen (YE)' },
]

export const BRAZILIAN_STATES = [
  { value: 'AC', label: 'Acre (AC)' },
  { value: 'AL', label: 'Alagoas (AL)' },
  { value: 'AP', label: 'Amapá (AP)' },
  { value: 'AM', label: 'Amazonas (AM)' },
  { value: 'BA', label: 'Bahia (BA)' },
  { value: 'CE', label: 'Ceará (CE)' },
  { value: 'DF', label: 'Distrito Federal (DF)' },
  { value: 'ES', label: 'Espírito Santo (ES)' },
  { value: 'GO', label: 'Goiás (GO)' },
  { value: 'MA', label: 'Maranhão (MA)' },
  { value: 'MT', label: 'Mato Grosso (MT)' },
  { value: 'MS', label: 'Mato Grosso do Sul (MS)' },
  { value: 'MG', label: 'Minas Gerais (MG)' },
  { value: 'PA', label: 'Pará (PA)' },
  { value: 'PB', label: 'Paraíba (PB)' },
  { value: 'PR', label: 'Paraná (PR)' },
  { value: 'PE', label: 'Pernambuco (PE)' },
  { value: 'PI', label: 'Piauí (PI)' },
  { value: 'RJ', label: 'Rio de Janeiro (RJ)' },
  { value: 'RN', label: 'Rio Grande do Norte (RN)' },
  { value: 'RS', label: 'Rio Grande do Sul (RS)' },
  { value: 'RO', label: 'Rondônia (RO)' },
  { value: 'RR', label: 'Roraima (RR)' },
  { value: 'SC', label: 'Santa Catarina (SC)' },
  { value: 'SP', label: 'São Paulo (SP)' },
  { value: 'SE', label: 'Sergipe (SE)' },
  { value: 'TO', label: 'Tocantins (TO)' },
]
